name: Comment on new issues

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Comment on issue with @actions/github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          node -e "
            const github = require('@actions/github');
            const token = process.env.GITHUB_TOKEN;
            const octokit = github.getOctokit(token);
            const context = github.context;

            const body = `# Willkommen im Nightly Support!

Hier ist es normal Bugs zu finden, da die Version ständig geupdatet wird.
Beschreibe uns das Problem und wir versuchen beim nächsten Patch den Bug zu fixen.

> __Automatische Nachricht__`;

            octokit.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              body: body
            });
          "
